#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define LL long long int
#define pb push_back
#define mp make_pair

using namespace std;

int F[105][105];
class CartInSupermarketEasy {
public:
	int fun(int n,int k){
	int res;
		if(F[n][k]!=-1)return F[n][k];
		else{
			if(n==0)return F[n][k]=0;
			res=fun(n-1,k)+1;
			if(k>0){
			for(int i=1;i<n;i++){
				for(int j=0;j<k;j++){
					res = min( max(fun(i,j),fun(n-i,k-j-1))+1,res ) ;
				}
			}
			}
		}
		return F[n][k]=res;
	}
	int calc(int N, int K) {
		for(int i=0;i<=N;i++)for(int j=0;j<K;j++)F[i][j]=-1;
		return fun(N,K);
	}	
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1;
	cout << "]" << endl;
	CartInSupermarketEasy *obj;
	int answer;
	obj = new CartInSupermarketEasy();
	clock_t startTime = clock();
	answer = obj->calc(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	int p0;
	int p1;
	int p2;
	
	{
	// ----- test 0 -----
	p0 = 5;
	p1 = 0;
	p2 = 5;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = 5;
	p1 = 2;
	p2 = 4;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = 15;
	p1 = 4;
	p2 = 6;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = 7;
	p1 = 100;
	p2 = 4;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = 45;
	p1 = 5;
	p2 = 11;
	all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	p0 = 100;
	p1 = 100;
	p2 = 8;
	all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// You have a sequence that consists of N shopping carts.
// You want to remove all of them as quickly as possible.
// 
// The process of removing the carts will consist of one or more turns.
// Each turn will take exactly one minute.
// At the beginning of each turn, you will have some sequences of carts.
// For each of those sequences you can choose between two options:
// 
// split it (in an arbitrary place) into two shorter sequences
// remove one shopping cart from the sequence
// 
// 
// There is one additional constraint: during the entire process you can only choose to split a sequence at most K times.
// 
// You are given the ints N and K.
// Compute and return the smallest number of minutes in which it is possible to remove all the carts.
// 
// DEFINITION
// Class:CartInSupermarketEasy
// Method:calc
// Parameters:int, int
// Returns:int
// Method signature:int calc(int N, int K)
// 
// 
// CONSTRAINTS
// -N will be between 1 and 100, inclusive.
// -K will be between 0 and 100, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// 5
// 0
// 
// Returns: 5
// 
// As K=0, you can never split any sequence. In each turn you have to remove one cart from your sequence. Hence, it will take 5 minutes to remove all 5 carts.
// 
// 1)
// 5
// 2
// 
// Returns: 4
// 
// One optimal solution: {5} -> {2,3} -> {1,2} -> {1,1} -> {}. We used two splits: once when splitting the sequence of 5 carts into 2+3 and the second time when  splitting the sequence of 2 carts into 1+1.
// 
// 2)
// 15
// 4
// 
// Returns: 6
// 
// 
// 
// 3)
// 7
// 100
// 
// Returns: 4
// 
// You don't have to split exactly K times.
// 
// 4)
// 45
// 5
// 
// Returns: 11
// 
// 
// 
// 5)
// 100
// 100
// 
// Returns: 8
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
