#include <bits/stdc++.h>
#define pb push_back
#define mp make_pair
typedef long long LL;
using namespace std;
bool filled[402][602];
int dx[] = {0,-1,0,1};
int dy[] = {1,0,-1,0};
int gret;
class grafixMask {
public:
	void fill(){
		for(int i=0;i<400;i++){
			for(int j=0;j<600;j++){
				filled[i][j] = false;
			}
		}
	}

	bool Valid(int x,int y){
		return x>=0 and x<400 and y<600 and y>=0 and filled[x][y] == false;
	}
	int dfs(int x,int y){
		int ret = 0;
		stack <pair<int,int> > S;
		S.push(make_pair(x,y));
		filled[x][y] = true;
		while(!S.empty()){
			pair <int,int> P = S.top();	
			S.pop();
			int X,Y;
			X = P.first;
			Y = P.second;
			ret++;
			for(int i=0;i<4;i++){
				if(Valid(X+dx[i],Y+dy[i])){
					filled[X+dx[i]][Y+dy[i]] = true ;
					S.push(make_pair(X+dx[i],Y+dy[i]));
				}
			}
		}
		return ret;
	}

	vector <int> sortedAreas(vector <string> rectangles) {
		fill();
		for(int i=0;i<rectangles.size();i++){
			int xx[4];
			for(int j=0;j<4;j++){
				xx[j] = 0;
			}
			for(int j=0,k=0;j<rectangles[i].size();j++){
				if(rectangles[i][j]==' '){
					k++;
					continue;
				}
				xx[k] = xx[k]*10 + rectangles[i][j] - '0';
			}
			for(int j=xx[0];j<=xx[2];j++){
				for(int k=xx[1];k<=xx[3];k++){
					filled[j][k] = true;
				}
			}
		}
		/*int vall = 0;
		for(int i=0;i<400;i++){
			for(int j=0;j<600;j++){
				if(!filled[i][j])
					vall++;
			}
		}
		cout << vall << endl;*/
		vector <int> ans;
		ans.clear();
		for(int i=0;i<400;i++){
			for(int j=0;j<600;j++){
				if(!filled[i][j]){
					gret = dfs(i,j);
					ans.push_back(gret);
				}
			}
		}
		for(int i=0;i<400;i++){
			for(int j=0;j<600;j++){
				assert(filled[i][j]==true);
			}
		}
		sort(ans.begin(), ans.end());
		return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, vector <int> p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	grafixMask *obj;
	vector <int> answer;
	obj = new grafixMask();
	clock_t startTime = clock();
	answer = obj->sortedAreas(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p1.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << p1[i];
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << answer[i];
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p1.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p1[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	vector <int> p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"0 292 399 307"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {116800,116800};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"48 192 351 207","48 392 351 407","120 52 135 547","260 52 275 547"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {22816,192608};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"0 192 399 207","0 392 399 407","120 0 135 599","260 0 275 599"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {22080,22816,22816,23040,23040,23808,23808,23808,23808};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"50 300 199 300","201 300 350 300","200 50 200 299","200 301 200 550"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {1,239199};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"0 20 399 20","0 44 399 44","0 68 399 68","0 92 399 92","0 116 399 116","0 140 399 140","0 164 399 164","0 188 399 188","0 212 399 212","0 236 399 236","0 260 399 260","0 284 399 284","0 308 399 308","0 332 399 332","0 356 399 356","0 380 399 380","0 404 399 404","0 428 399 428","0 452 399 452","0 476 399 476","0 500 399 500","0 524 399 524","0 548 399 548","0 572 399 572","0 596 399 596","5 0 5 599","21 0 21 599","37 0 37 599","53 0 53 599","69 0 69 599","85 0 85 599","101 0 101 599","117 0 117 599","133 0 133 599","149 0 149 599","165 0 165 599","181 0 181 599","197 0 197 599","213 0 213 599","229 0 229 599","245 0 245 599","261 0 261 599","277 0 277 599","293 0 293 599","309 0 309 599","325 0 325 599","341 0 341 599","357 0 357 599","373 0 373 599","389 0 389 599"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {15,30,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,100,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,200,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// 
// Note: This problem statement includes images that may not appear
// if you are using a plugin. For best results, use the Arena editor.
// 
// 
// 
// 
// In one mode of the grafix software package, the user blocks off portions
// of a masking layer using opaque rectangles. The bitmap used as the masking
// layer is 400 pixels tall and 600 pixels wide. Once the rectangles have
// been blocked off, the user can perform painting actions through the
// remaining areas of the masking layer, known as holes. To be
// precise, each hole is a maximal collection of contiguous pixels that
// are not covered by any of the opaque rectangles. Two pixels are contiguous
// if they share an edge, and contiguity is transitive.
// 
// 
// 
// 
// You are given a vector <string> named rectangles, the
// elements of which specify the rectangles that have been blocked off
// in the masking layer. Each string in rectangles consists of four
// integers separated by single spaces, with no additional spaces in the
// string. The first two integers are the window coordinates of the
// top left pixel in the given rectangle, and the last two integers are
// the window coordinates of its bottom right pixel. The window coordinates
// of a pixel are a pair of integers specifying the row number and column
// number of the pixel, in that order. Rows are numbered from top to bottom,
// starting with 0 and ending with 399. Columns are numbered from left to
// right, starting with 0 and ending with 599.
// Every pixel within and along the border of the rectangle defined by these
// opposing corners is blocked off.
// 
// 
// 
// 
// Return a vector <int> containing the area, in pixels, of every
// hole in the resulting masking area, sorted from smallest area to greatest. 
// 
// 
// 
// 
// DEFINITION
// Class:grafixMask
// Method:sortedAreas
// Parameters:vector <string>
// Returns:vector <int>
// Method signature:vector <int> sortedAreas(vector <string> rectangles)
// 
// 
// NOTES
// -Window coordinates are not the same as Cartesian coordinates. Follow the definition given in the second paragraph of the problem statement.
// 
// 
// CONSTRAINTS
// -rectangles contains between 1 and 50 elements, inclusive
// -each element of rectangles has the form "ROW COL ROW COL", where: "ROW" is a placeholder for a non-zero-padded integer between 0 and 399, inclusive; "COL" is a placeholder for a non-zero-padded integer between 0 and 599, inclusive; the first row number is no greater than the second row number; the first column number is no greater than the second column number
// 
// 
// EXAMPLES
// 
// 0)
// {"0 292 399 307"}
// 
// Returns: { 116800,  116800 }
// 
// The masking layer is depicted below in a 1:4 scale diagram.
// 
// 
// 
// 
// 
// 1)
// {"48 192 351 207", "48 392 351 407", "120 52 135 547", "260 52 275 547"}
// 
// Returns: { 22816,  192608 }
// 
// 
// 
// 
// 
// 
// 2)
// {"0 192 399 207", "0 392 399 407", "120 0 135 599", "260 0 275 599"}
// 
// Returns: { 22080,  22816,  22816,  23040,  23040,  23808,  23808,  23808,  23808 }
// 
// 
// 
// 
// 
// 
// 3)
// {"50 300 199 300", "201 300 350 300", "200 50 200 299", "200 301 200 550"}
// 
// Returns: { 1,  239199 }
// 
// 4)
// {"0 20 399 20", "0 44 399 44", "0 68 399 68", "0 92 399 92",
//  "0 116 399 116", "0 140 399 140", "0 164 399 164", "0 188 399 188",
//  "0 212 399 212", "0 236 399 236", "0 260 399 260", "0 284 399 284",
//  "0 308 399 308", "0 332 399 332", "0 356 399 356", "0 380 399 380",
//  "0 404 399 404", "0 428 399 428", "0 452 399 452", "0 476 399 476",
//  "0 500 399 500", "0 524 399 524", "0 548 399 548", "0 572 399 572",
//  "0 596 399 596", "5 0 5 599", "21 0 21 599", "37 0 37 599",
//  "53 0 53 599", "69 0 69 599", "85 0 85 599", "101 0 101 599",
//  "117 0 117 599", "133 0 133 599", "149 0 149 599", "165 0 165 599",
//  "181 0 181 599", "197 0 197 599", "213 0 213 599", "229 0 229 599",
//  "245 0 245 599", "261 0 261 599", "277 0 277 599", "293 0 293 599",
//  "309 0 309 599", "325 0 325 599", "341 0 341 599", "357 0 357 599",
//  "373 0 373 599", "389 0 389 599"}
// 
// Returns: { 15,  30,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  100,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  115,  200,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  230,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  300,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345,  345 }
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
