#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define LL long long int
#define pb push_back
#define mp make_pair

using namespace std;


class TopView {
public:
	string findOrder(vector <string> grid) {
		
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, string p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	TopView *obj;
	string answer;
	obj = new TopView();
	clock_t startTime = clock();
	answer = obj->findOrder(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p1 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	string p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"..AA..",".CAAC.",".CAAC."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "CA";
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"..47..","..74.."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "ERROR!";
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"bbb666",".655X5","a65AA5","a65AA5","a65555"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "65AXab";
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"aabbaaaaaaaaaaaaaaaaaa","aabbccccccccccccccaaaa","aab11111ccccccccccaaaa","aab12221ccccccccccaaaa","aab12221ccccccccccaaaa","aab12221ccccccccccaaaa","aab12221ccccccccccaaaa","aab12221ccccccccccaaaa","aab12221ddddddddddaaaa","aab13331DDDDDDDDDDaaaa","aab13331DDDDDDDDDDaaaa","aa.11111DDDDDDDDDDaaaa","aaaaaaaaaaaaaaaaaaaaaa"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "ERROR!";
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Ralph was once playing with a set of cards and a grid of cells.
// Each card was a rectangle of a unique color.
// Different cards may have had different dimensions.
// Ralph took his cards one at a time, and placed each of them onto the grid.
// When placing a card, Ralph aligned its sides with grid lines, so each card covered some rectangular block of cells.
// Some cards may have overlapped other, previously placed cards partially or even completely.
// Once all the cards were placed, on each cell only the topmost card was visible.
// 
// You are given a vector <string> grid that describes what Ralph could see after placing the cards. The j-th character of element i of grid is '.' if the cell at position (i,j) is empty (does not contain any card) or is an alphanumeric character that represents the only color Ralph could see when looking at the cell.
// 
// Ralph does not remember the order he used to place the cards. Write a program that finds the order in which the cards of each visible color were placed.  The return value should be a string, containing exactly once each of the alphanumeric characters that occur in grid.
// The i-th character of the return value should be the color of the i-th card (0-based index) that Ralph placed.
// In case there are multiple valid orders, return the lexicographically smallest one.
// In case there is no valid order of colors, return "ERROR!" (quotes for clarity).
// 
// DEFINITION
// Class:TopView
// Method:findOrder
// Parameters:vector <string>
// Returns:string
// Method signature:string findOrder(vector <string> grid)
// 
// 
// NOTES
// -The letters in grid are case-sensitive: 'a' and 'A' are distinct colors.
// -The lexicographically smaller of two strings of equal length is the one that has the earlier character (using ASCII ordering) at the first position at which they differ.
// 
// 
// CONSTRAINTS
// -grid will contain between 1 and 50 elements, inclusive.
// -Each element of grid will contain between 1 and 50 characters, inclusive.
// -All elements of grid will contain the same number of characters.
// -Each character in each element of grid will be a period ('.'), an uppercase letter ('A'-'Z'), a lowercase letter ('a'-'z'), or a digit ('0'-'9').
// -At least one character in grid will be different from '.'.
// 
// 
// EXAMPLES
// 
// 0)
// {"..AA..",
//  ".CAAC.",
//  ".CAAC."}
// 
// Returns: "CA"
// 
// The card with color C is a rectangle of 2 rows and 4 columns. The card with color A, a rectangle of 3 rows and 2 columns, was placed on top of it.
// 
// 1)
// {"..47..",
//  "..74.."}
// 
// 
// Returns: "ERROR!"
// 
// Each card has a unique color, this top perspective view tells us about 2 cards. This setting is not possible without using multiple cards of color 4 or 7.
// 
// 2)
// {"bbb666",
//  ".655X5",
//  "a65AA5",
//  "a65AA5",
//  "a65555"}
// 
// Returns: "65AXab"
// 
// 
// 
// 3)
// {"aabbaaaaaaaaaaaaaaaaaa",
//  "aabbccccccccccccccaaaa",
//  "aab11111ccccccccccaaaa",
//  "aab12221ccccccccccaaaa",
//  "aab12221ccccccccccaaaa",
//  "aab12221ccccccccccaaaa",
//  "aab12221ccccccccccaaaa",
//  "aab12221ccccccccccaaaa",
//  "aab12221ddddddddddaaaa",
//  "aab13331DDDDDDDDDDaaaa",
//  "aab13331DDDDDDDDDDaaaa",
//  "aa.11111DDDDDDDDDDaaaa",
//  "aaaaaaaaaaaaaaaaaaaaaa"}
// 
// Returns: "ERROR!"
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
